school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("manage/", include('management.urls')),
    path("finance/", include('finance.urls')),
    path("", include('authman.urls')),
    path("academics/", include('academics.urls')),
    path("leave/", include('leave.urls')),
    path("reports/", include('reports.urls')),
    path("results/", include('results.urls')),
    path("staff/", include('staff.urls')),
     path("grading/", include('grading.urls')),
    path("timetable/", include('timetable.urls')),
    path("students/", include('students.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# default: "Django Administration"
admin.site.site_header = 'Backend Administration'
# default: "Site administration"
admin.site.index_title = 'Backend Admin Area'
admin.site.site_title = 'Backend Administration'

staff/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    # management
    path("staff/home/", staff_home, name='staff_home'),
    path("staff/apply/leave/", staff_apply_leave,
         name='staff_apply_leave'),
    path("staff/feedback/", staff_feedback, name='staff_feedback'),
    path("staff/view/profile/", staff_view_profile,
         name='staff_view_profile'),
    path("staff/attendance/take/", staff_take_attendance,
         name='staff_take_attendance'),
    path("staff/attendance/update/", staff_update_attendance,
         name='staff_update_attendance'),
    path("staff/get_students/", get_students, name='get_students'),
    path("staff/attendance/fetch/", get_student_attendance,
         name='get_student_attendance'),
    path("staff/attendance/save/",
         save_attendance, name='save_attendance'),
    path("staff/attendance/update/",
         update_attendance, name='update_attendance'),
    path("staff/fcmtoken/", staff_fcmtoken, name='staff_fcmtoken'),
    path("staff/view/notification/", staff_view_notification,
         name="staff_view_notification"),
]

leave/models.py
from django.db import models
from authman.models import *

# Create your models here.
class LeaveReportStudent(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    date = models.CharField(max_length=60)
    message = models.TextField()
    status = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
       return self.message


class LeaveReportStaff(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    date = models.CharField(max_length=60)
    message = models.TextField()
    status = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
       return self.message

templates/staff_template/edit_student_result.html
{% extends 'management/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                    <form method="POST">
                        {% csrf_token %}
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>


                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">




                 {{ form }}

                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" id='update_result' class="btn btn-primary btn-block">Update Result</button>

                    </div>
                </form>
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}


{% block custom_js %}
<script>
    $(document).ready(function () {
        $("#id_subject").change(function () {
            fetchStudents();
            });
            $("#id_session_year").change(function () {
                fetchStudents();
                });
   $("#id_student").change(function () {
    fetch_student_result();
                });
                $("#id_exam").hide()
                $("#id_test").hide()
                $("#update_result").hide()
                $('label[for="id_test"]').hide();
                $('label[for="id_exam"]').hide();
        function fetchStudents(){
            var subject = $("#id_subject").val()
            var session = $("#id_session_year").val()
            $("#id_student").html(null)
            if (session.length  == 0 || subject.length == 0 || session < 1 || subject < 1){
                return false;
            }
            $.ajax({
                url: "{% url 'get_students' %}",
                type: 'POST',
                data: {
                    subject: subject,
                    session:session
                }
            }).done(function (response) {
                var json_data = JSON.parse(response)
                if (json_data.length < 1) {
                    alert("No data to display")
                } else {
                    var div_data = "<option>Select Student</option>"

                    for (key in json_data) {
                        div_data += "<option value='" + json_data[key]['id'] + "'>" + json_data[key]['name'] + " </option>"
                    }

                    $("#id_student").html(div_data)
                }
            }).fail(function (response) {
                alert("Error in fetching students")
            })
               }

               function fetch_student_result(){
                var student = $("#id_student").val()
                var subject = $("#id_subject").val()
                $("#id_test").val(null)
                $("#id_exam").val(null)
                $("#id_exam").hide()
                $("#update_result").hide()
                $("#id_test").hide()
                $('label[for="id_test"]').hide();
                $('label[for="id_exam"]').hide();
                if (student.length  == 0 || subject.length == 0 || student < 1 || subject < 1){
                    return false;
                }
                $.ajax({
                    url: "{% url 'fetch_student_result' %}",
                    type: 'POST',
                    data: {
                        subject: subject,
                        student:student
                    }
                }).done(function (response) {
                    if (response == 'False') {
                        alert("No data to display")
                    } else {
                        var json_data = JSON.parse(response)

                            $("#id_test").val(json_data['test'])
                            $("#id_exam").val(json_data['exam'])
                            $("#id_exam").show()
                            $("#id_test").show()
                            $("#update_result").show()
                            $('label[for="id_test"]').show();
                            $('label[for="id_exam"]').show();

                    }
                }).fail(function (response) {
                    alert("Error in fetching students")
                })
               }

    })
</script>
{% endblock custom_js %}

templates/staff_template/home_content.html
{% extends 'management/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3>{{total_students}}</h3>

                        <p>Total Students</p>
                    </div>
                    <div class="icon">
                      <i class="nav-icon fas fa-user-graduate"></i>
                    </div>

                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                        <h3>{{total_attendance}}</h3>

                        <p>Total Attendance Taken</p>
                    </div>
                    <div class="icon">
                      <i class="nav-icon fas fa-calendar-alt"></i>
                    </div>

                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-maroon">
                    <div class="inner">
                        <h3>{{total_leave}}</h3>

                        <p>Total Leave Applied</p>
                    </div>
                    <div class="icon">
                      <i class="nav-icon fas fa-sign-out-alt"></i>
                    </div>

                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        <h3>{{total_subject}}</h3>

                        <p>Total Subjects</p>
                    </div>
                    <div class="icon">
                      <i class="nav-icon fas fa-book"></i>
                    </div>

                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <div class="row">
            <div class="col-md-6">
                <!-- LINE CHART -->
                <div class="card card-secondary">
                  <div class="card-header">
                    <h3 class="card-title">{{page_title}}</h3>

                    <div class="card-tools">
                      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                      </button>
                      <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                    </div>
                  </div>
                  <div class="card-body">
                    <div class="chart">
                      <canvas id="pieChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                    </div>
                  </div></div>
                  <!-- /.card-body -->
                </div>
                <div class="col-md-6">
                    <div class="card card-secondary">
              <div class="card-header">
                <h3 class="card-title">{{page_title}}</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                  </button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">
                <div class="chart">
                  <canvas id="barChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
                </div>
            <!-- right col -->
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
{% endblock content %}

{% block custom_js %}
  <script>
      $(document).ready(function(){
        var donutData        = {
            labels: ['Attendance', 'Leave'],
            datasets: [
              {
                data:[{{total_attendance}}, {{total_leave}}],
                backgroundColor : ['#00a65a', '#f39c12',],
              }
            ]
          }
        var pieChartCanvas = $('#pieChart').get(0).getContext('2d')
        var pieData        = donutData;
        var pieOptions     = {
          maintainAspectRatio : false,
          responsive : true,
        }
        //Create pie or douhnut chart
        // You can switch between pie and douhnut using the method below.
        var pieChart = new Chart(pieChartCanvas, {
          type: 'pie',
          data: pieData,
          options: pieOptions
        });

        var subject_list = {{ subject_list|safe|escape }};
        var attendance_list = {{ attendance_list }};

            var barChartData = {
      labels  : subject_list,
      datasets: [
      {
        label               : 'Attendance Per Subject',
        backgroundColor     : '#17A2B8',
        borderColor         : 'rgba(60,141,188,0.8)',
        pointRadius          : false,
        pointColor          : '#3b8bba',
        pointStrokeColor    : 'rgba(60,141,188,1)',
        pointHighlightFill  : '#fff',
        pointHighlightStroke: 'rgba(60,141,188,1)',
        data                : attendance_list
      },

      ]
    }
        var barChartCanvas = $('#barChart').get(0).getContext('2d')
        var temp0 = barChartData.datasets[0]
        //var temp1 = areaChartData.datasets[1]
        barChartData.datasets[0] = temp0
       // barChartData.datasets[1] = temp0

    var stackedBarChartOptions = {
      responsive              : true,
      maintainAspectRatio     : false,
      scales: {
        xAxes: [{
          stacked: true,
        }],
        yAxes: [{
          stacked: true
        }]
      }
    }

        var barChart = new Chart(barChartCanvas, {
          type: 'bar',
          data: barChartData,
          options: stackedBarChartOptions
        })
      })


  </script>
      <!-- The core Firebase JS SDK is always required and must be listed first -->
      <script src="https://www.gstatic.com/firebasejs/7.23.0/firebase-app.js"></script>

      <!-- TODO: Add SDKs for Firebase products that you want to use
       https://firebase.google.com/docs/web/setup#available-libraries -->
      <script src="https://www.gstatic.com/firebasejs/7.23.0/firebase-analytics.js"></script>
      <script src="https://www.gstatic.com/firebasejs/7.22.1/firebase-messaging.js"></script>


      <script>
          // Your web app's Firebase configuration
          // For Firebase JS SDK v7.20.0 and later, measurementId is optional
          var firebaseConfig = {
              apiKey: "AIzaSyBarDWWHTfTMSrtc5Lj3Cdw5dEvjAkFwtM",
              authDomain: "sms-with-django.firebaseapp.com",
              databaseURL: "https://sms-with-django.firebaseio.com",
              projectId: "sms-with-django",
              storageBucket: "sms-with-django.appspot.com",
              messagingSenderId: "945324593139",
              appId: "1:945324593139:web:03fa99a8854bbd38420c86",
              measurementId: "G-2F2RXTL9GT"
          };
          // Initialize Firebase
          firebase.initializeApp(firebaseConfig)
          const messaging = firebase.messaging();
          function InitializeFireBaseMessaging() {
              messaging
                  .requestPermission()
                  .then(function () {
                      console.log("Notification Permission");
                      return messaging.getToken();
                  })
                  .then(function (token) {
                      console.log("Token : " + token);
                      sendToServer(token);
                  })
                  .catch(function (reason) {
                      console.log(reason)
                  })
          }
          messaging.onMessage(function (payload) {
              const notificationOption = {
                  body: payload.notification.body,
                  icon: payload.notification.icon,

              }
              if (Notification.permission == 'granted') {
                  var notification = new Notification(payload.notification.title, notificationOption);
                  notification.onclick = function (event) {
                      event.preventDefault();
                      window.open(payload.notification.click_action, "_blank");
                      notification.close();
                  }
              }
              console.log(payload);
          });
          messaging.onTokenRefresh(function () {
              messaging.getToken()
                  .then(function (newToken) {
                      console.log("New Token : " + newToken);
                      sendToServer(newToken);

                  })
                  .catch(function (reason) {
                      console.log(reason)
                  })
          })

          function sendToServer(token){
            $.ajax({
              url: "{% url 'staff_fcmtoken' %}",
              type: 'POST',
              data: {
                  token: token,
              }
          }).done(function (response) {


          }).fail(function (response) {
          })

          }

          InitializeFireBaseMessaging();
      </script>
{% endblock custom_js %}

templates/staff_template/staff_add_result.html
{% extends 'management/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                    <form method="POST">
                        {% csrf_token %}
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>


                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">


                        <div class="form-group">
                            <label>Subject</label>
                            <select name="subject" class="form-control" id='subject'>
                                <option value="">----</option>
                                {% for subject in subjects  %}
                                <option value="{{subject.id}}">{{subject.name}}</option>
                                {% endfor %}
                            </select>
                        </div>


                        <div class="form-group">
                            <label>Session Year</label>
                            <select name="session" id='session' class="form-control">
                                <option value="">----</option>
                                {% for session in sessions  %}
                                <option value="{{session.id}}">{{session}} </option>
                                {% endfor %}
                            </select>
                        </div>


                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="button" id='fetch_student' class="btn btn-primary btn-block">Fetch
                            Students</button>
                        <div class="form-group" id="student_data">

                        </div>
                    </div>
                </form>
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}


{% block custom_js %}
<script>
    $(document).ready(function () {


        $("#fetch_student").click(function () {
            var subject = $("#subject").val()
            var session = $("#session").val()
            $("#student_data").html(null)
if (subject.length  == 0 || session.length == 0){
    alert("Please select session and subject");
    return false;
}
            $.ajax({
                url: "{% url 'get_students' %}",
                type: 'POST',
                data: {
                    subject: subject,
                    session: session
                }
            }).done(function (response) {
                var json_data = JSON.parse(response)
                if (json_data.length < 1) {
                    alert("No data to display")
                } else {
                    var div_data = "<hr/><div class='form-group'> <label> Student List</label> <select class='student_list form-control' name='student_list'> "

                    for (key in json_data) {
                        div_data += "<option value='" + json_data[key]['id'] + "'>" + json_data[key]['name'] + " </option>"
                    }
                    div_data += "</select></div>"
                    div_data += "<div class='form-group row'> <div class='col-md-6'> <label> Test Score </label> <input class='form-control' name='test' placeholder='Test Score' max='40' min='0' required type='number' /></div><div class='col-md-6'><label> Exam Score </label>  <input class='form-control' placeholder='Exam Score'  name='exam' max='60' min='0' required type='number' /> </div></div><div class='form-group'><button id='save_attendance' class='btn btn-success' type='submit'>Save Result</button></div></div>"
                    $("#student_data").html(div_data)
                }
            }).fail(function (response) {
                alert("Error in fetching students")
            })




        })
    })
</script>
{% endblock custom_js %}

templates/staff_template/staff_apply_leave.html
{% extends 'management/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "management/form_template.html" with messages=messages  form=form button_text="Apply For Leave"%}
                </div>
                <!-- /.card -->
<div class="card card-default">
    <div class="card-header"><h3 class="card-title"><b>Leave History</b></h3>
   <div class="table">

       <table class="table table-bordered table-hover">
           <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Message</th>
             <th>Status</th>
         </tr>
           </thead>
        {% for leave in leave_history %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{leave.date}}</td>
              <td>{{leave.message}}</td>
              <td>

                  {% if leave.status == 0 %}
                  <span class="badge badge-warning">Pending</span>
                  {% elif leave.status == 1 %}
                  <span class="badge badge-success">Accepted</span>

                    {% else %}
                    <span class="badge badge-danger">Rejected</span>

                    {% endif %}

                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/staff_template/staff_feedback.html
{% extends 'management/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "management/form_template.html" with messages=messages  form=form button_text="Submit Feedback"%}
                </div>
                <!-- /.card -->
<div class="card card-dark">
    <div class="card-header"><h3 class="card-title">{{page_title}}</h3>
    </div>
   <div class="table p-2">

       <table class="table table-bordered">
           <tr>
               <th>ID</th>
               <th>Feedback</th>
               <th>Reply</th>
            <th>Created At</th>
        </tr>
        {% for feedback in feedbacks %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{feedback.feedback}}</td>
              <td>

                  {% if feedback.reply == "" %}
                      <p class="badge badge-warning">No Response Yet</p>
                      {% else %}
                      {{feedback.reply}}
                  {% endif %}

              </td>
              <td>{{feedback.created_at}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/staff_template/staff_take_attendance.html
{% extends 'management/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">



                        <div class="form-group">
                            <label>Subject</label>
                            <select name="subject" class="form-control" id='subject'>
                                <option value="">----</option>
                                {% for subject in subjects  %}
                                <option value="{{subject.id}}">{{subject.name}}</option>
                                {% endfor %}
                            </select>
                        </div>


                        <div class="form-group">
                            <label>Class</label>
                            <select name="class_id" id='class_id' class="form-control">
                                <option value="">----</option>
                                {% for class in classes  %}
                                <option value="{{class.id}}">{{class}} </option>
                                {% endfor %}
                            </select>
                        </div>
                        {% comment %}

                        <div>
                            <label>Attendance Date</label>
                            <input type="date" class='form-control' name="attendance_date" id='attendance_date' id="">
                        </div>
                        {% endcomment %}

                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="button" id='fetch_student' class="btn btn-success btn-block">Fetch Students</button>
                        <div class="form-group" id="student_data">

                        </div>
                    </div>
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}


{% block custom_js %}
<script>
    $(document).ready(function () {


        $("#fetch_student").click(function () {
            var subject = $("#subject").val()
            var class_id = $("#class_id").val()
            $("#student_data").html(null)
if (subject.length  == 0 || class_id.length == 0){
    alert("Please select class and subject");
    return false;
}
            $.ajax({
                url: "{% url 'get_students' %}",
                type: 'POST',
                data: {
                    subject: subject,
                    class_id: class_id
                }
            }).done(function (response) {
                var json_data = JSON.parse(response)
                if (json_data.length < 1) {
                    alert("No data to display")
                } else {
                    var div_data = "<hr/><div class='form-group'></div><div class='form-group'> <label>Attendance Date</label><input type='date' class='form-control' name='attendance_date' id='attendance_date' ><div class='row'>"

                    for (key in json_data) {
                        div_data += "<div class='col-lg-3'><div class='form-check custom-control custom-checkbox'><input type='checkbox' class='custom-control-input' checked='checked' name='student_data[]' value=" + json_data[key]['id'] + " id='checkbox" + json_data[key]['id'] + "' /> <label for='checkbox" + json_data[key]['id'] + "' class='custom-control-label'>" + json_data[key]['name'] + "</label></div> </div>"
                    }
                    div_data += "</div></div>"
                    div_data += "<div class='form-group'><button id='save_attendance' class='btn btn-success' type='button'>Save Attendance</button></div>"
                    $("#student_data").html(div_data)
                }
            }).fail(function (response) {
                alert("Error in fetching students")
            })


            $(document).on('click', '#save_attendance', function () {
                $(this).attr("disabled","disabled")
                $(this).text("Saving Attendance Data...")
                var student_data = $("input[name='student_data[]']").map(function () {
                    if ($(this).is(":checked")){
                    return {'id':$(this).val(), 'status': 1};

                    }
                    return {'id':$(this).val(), 'status': 0};

                }).get()
                var attendance_date = $('#attendance_date').val()
                if (attendance_date.length < 10){
                    alert("Select date")
                    return false;
                }
                student_data = JSON.stringify(student_data)
                $.ajax({
                    url: "{% url 'save_attendance' %}",
                    type: 'POST',
                    data: {
                        date: attendance_date,
                        student_ids: student_data,
                        subject: subject,
                        class_id: class_id
                    }
                }).done(function (response) {
                    if (response == 'OK'){
                        alert("Saved")
                    }else{
                        alert("Error. Please try again")
                    }
                    location.reload()

                }).fail(function (response) {
                    alert("Error in saving attendance")
                })

            })


        })
    })
</script>
{% endblock custom_js %}